spring:
  datasource:
     url: jdbc:postgresql://3.69.157.49:5432/market
     username: postgres
     password: MuRaD198852_Mmm
  jpa:
     hibernate:
       ddl-auto: update
     show-sql: true
  output:
     ansi:
       enabled: always
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8801/eureka
      
logging:
  level:
    org:
      springframework:
        security: debug
debug: true

ftp:
  server:
    host: 3.69.157.49
    port: 21
    username: market
    password: MuRaD198852_Mmm
    directory: /images
